spring:
  application:
    name: eShopEule

  datasource:
    url: jdbc:postgresql://localhost:5432/eShopEule
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: eshop27test@gmail.com
    password: vgjzmzepofhxuqjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      authentication-database: admin
      database: eShopEule
      username: superpech
      password: 123456789
      port: 27017
      host: localhost

server:
  port: 8080

logging:
  level:
    org:
      senju:
        eshopeule: DEBUG

bootstrap:
  account:
    super-admin:
      email : superadmin@eule.com
      username: superadmin
      phone: 0123456789
      password: Abc123456@

security:
  verify-code:
    expiration: 300
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token:
      expiration: 86400000
    refresh-token:
      expiration: 604800000
  oauth2:
    client:
      registration:
        google:
          client-id: 353684858508-di8dg1ilh3ee6h1vmbo7gmb1hou22l52.apps.googleusercontent.com
          client-secret: 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
        github:
          client-id: Ov23liAImsFOfFwbp9X8
          client-secret: bdf2665263f92d96a2b88923ed08d772e68915e2
        discord:
          client-id: 1220756198157189151
          client-secret: PNhWDeeFTSmqm0dfSS0O_-qV4UP5JJ08

twilio:
  account-sid: AC6c18541e060f12cb646a2a50fd49f984
  auth-token: 5b6e5412d576e151b8e2f12627b8d347
  phone-number: +16502678582

firebase:
  storage-bucket: eshopeule.appspot.com