spring:
  application:
    name: eShopEule
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}
    connection-timeout: 10m
    socket-timeout: 1h
    socket-keep-alive: true

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml

server:
  port: 8080

logging:
  level:
    org:
      senju:
        eshopeule: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui

bootstrap:
  account:
    super-admin:
      email : superadmin@eule.com
      username: superadmin
      phone: 0123456789
      password: Abc123456@

security:
  verify-code:
    expiration: 300
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token:
      expiration: 86400000
    refresh-token:
      expiration: 604800000
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
        github:
          client-id: ${GITHUB_CLIENT_ID}
          client-secret: ${GITHUB_CLIENT_SECRET}
        discord:
          client-id: ${DISCORD_CLIENT_ID}
          client-secret: ${DISCORD_CLIENT_SECRET}

twilio:
  account-sid: ${TWILIO_ACC_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: +16502678582

firebase:
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}
  image-url: https://storage.googleapis.com/${firebase.storage-bucket}/%s