spring:
  application:
    name: eShopEule
  config:
    import: optional:file:secrets.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/eShopEule
    username: postgres
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
    uri: ${mongodb.uri}
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10m
    socket-timeout: 1h
    socket-keep-alive: true

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml

server:
  port: 8080

logging:
  level:
    org:
      senju:
        eshopeule: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui

bootstrap:
  account:
    super-admin:
      email : superadmin@eule.com
      username: superadmin
      phone: 0123456789
      password: Abc123456@

security:
  verify-code:
    expiration: 300
  jwt:
    secret-key: ${jwt.sk}
    access-token:
      expiration: 86400000
    refresh-token:
      expiration: 604800000
  oauth2:
    client:
      registration:
        google:
          client-id: ${google.client-id}
          client-secret: ${google.client-secret}
        github:
          client-id: ${github.client-id}
          client-secret: ${github.client-secret}
        discord:
          client-id: ${discord.client-id}
          client-secret: ${discord.client-secret}

twilio:
  account-sid: ${twilio.acc-sid}
  auth-token: ${twilio.auth-token}
  phone-number: +16502678582

firebase:
  storage-bucket: ${firebase.sb}
  image-url: https://storage.googleapis.com/${firebase.storage-bucket}/%s